Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (1, N'Nét nhà', N'CB020',14,1,0,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (1, N'Đường mép nước', N'NG020',30,0,0,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (1, N'Lòng đường', N'LD',22,0,0,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (1, N'Đường bờ nước', N'NG010',31,1,0,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (1, N'Kí hiệu nghĩa địa', N'NGHIADIA',19,0,0,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (1, N'Địa giới cấp xã', N'AC031',46,0,0,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (1, N'Địa giới cấp huyện', N'AC021',44,0,0,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (1, N'Kênh mương', N'DTL',32,0,0,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (1, N'Cầu đường bộ', N'HG020',27,0,0,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (1, N'Cống', N'CONG',26,0,0,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (1, N'Cột Điện', N'COTDIEN',55,0,0,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (1, N'Lăng Mộ', N'MO',18,0,0,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (1, N'Hướng dòng chảy', N'HDC',39,0,0,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (1, N'Trạm Biến thế', N'TRAMBT',17,0,0,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (1, N'Ranh giới thửa đất', N'IA120',10,1,1,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (1, N'Chỉ giới đường sắt', N'GS2',21,1,1,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (1, N'Chỉ giới đường bộ', N'GB2',23,1,1,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (1, N'Kênh, mương, rãnh thoát nước', N'TV3',32,1,1,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (1, N'Đường giới hạn chân đê', N'TD21',38,1,1,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (1, N'Ký hiệu', N'Symbol',19,0,0,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (1, N'Khung bản đồ', N'KHUNG',63,0,0,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (1, N'Ký hiệu', N'Symbol',39,0,0,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (2, N'Dạng Text', N'TEXT',28,0,1,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (2, N'Khung bản đồ p', N'KHUNGP',63,0,0,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (3, N'Cầu', N'HG020',27,0,NULL,0)
Insert into THAMSO_BDDC (Loai, Ten, Kyhieu, Lop, Nhap, Lichsu, DTPhucvu) values (3, N'Khung bản đồ', N'KHUNG',63,0,NULL,0)
